### ISSUE TITLE
Change the title of a column in the Runs list

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/tailer-studio#286]
**Is your feature request related to a problem? Please describe.**
Change the name of the Workflow Id Bucket to Configuration Id like in the Configurations list

**Describe the solution you'd like**
https://cdn.zappy.app/1e7a1f05a3e1f6047674702ad8923a19.png

**Comment by Eronne** [comment]
Closing this because it has already been implemented.
@romone22 feel free to reopen the issue if this is not the case.
