### ISSUE TITLE
Replace the Airflow link with a new icon when the run is in direct execution mode

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/tailer-studio#291]
**Is your feature request related to a problem? Please describe.**
The TTT and tomorrow TTS configuration with the direct execution flag ("direct_execution": true) are not using Airflow as the orchestrator engine. So the airflow access in the TTT and TTS listing is not relevant in this case.

**Describe the solution you'd like**
Suppress the Airflow link when the run as the "direct_execution": true flag (in the path configuration_contex/configuration/)
Replace it with a green icon as a rocket without link

**Comment by Eronne** [comment]
Actually, the AirFlow is displayed only for super admins. Is this still the case or do we only check for `direct_execution` flag?

**Comment by Eronne** [comment]
So there is a rocket present for configurations ? Because they don't have the `direct_execution` property.
